zendesk/zcli

.github/workflows/test.yml
packages/zcli-apps/src/utils/appConfig.test.ts
packages/zcli-apps/tests/functional/package.test.ts
packages/zcli-core/src/lib/config.test.ts
packages/zcli-core/src/lib/config.ts

We just enabled our workflow to run tests on all major platforms and i found that tests around package and app config path were failing. This makes sense given paths are shaped little directly on windows.
This PR fixes,
- Unit and functional tests for windows.
- Global config readJson bug (This was caused by introduction json formatting, which i am removing for now)

Patch tests for windows and fix a config read bug

---

.github/workflows/test.yml

Update node setup action so that all builds pass. At the moment node setup fails because Github has deprecated set-env and add-path commands
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Update node-setup in actions

---

packages/zcli-apps/src/lib/buildAppJSON.ts
packages/zcli-apps/src/utils/createApp.ts

`zcli apps:server` will prompt for missing param options but it does not allow you to skip with Return key like zat.
Fixes this issue https://github.com/zendesk/zcli/issues/16

Make apps server settings prompt optional

---

docs/apps.md
packages/zcli-apps/src/lib/buildAppJSON.ts
packages/zcli-apps/src/types.ts

This does not work for ZCLI
https://developer.zendesk.com/apps/docs/developer-guide/using_sdk#testing-an-app-with-secure-settings-locally
https://github.com/zendesk/zcli/issues/22
This PR fixes above issue by adding installation id support for zcli apps server's app.json

Add installation id support for local testing

---

packages/zcli-core/src/lib/auth.test.ts
packages/zcli-core/src/lib/auth.ts
packages/zcli-core/src/lib/request.test.ts

zcli unattended auth fails when using API token.
Issue was caused due to adding a `/` after `token` instead of in front of it.  🤦 
1. set your credentials
```
➜  export ZENDESK_SUBDOMAIN='z3ntest'
➜  export ZENDESK_PASSWORD='password'
➜  export ZENDESK_EMAIL='sasangi@zendesk.com'
```
2 `yarn dev apps:validate ./you-app`
3. your should not get 403

Fix api token basic auth token generation

---

docs/apps.md

As we are no longer able to support `--config` option in `apps:server` while supporting multiple apps, this has been removed from the apps:server documentation.

[update-documentation] Remove config option from apps:server doc

---

packages/zcli-apps/package.json
packages/zcli-apps/src/commands/apps/new.ts
packages/zcli-apps/src/types.ts
yarn.lock

@zendesk/vegemite 
We should use the new app_scaffolds monorepo for all zcli app scaffolds going forward.
For more information, see https://github.com/zendesk/app_scaffolds.

[VEG-600] Use new app_scaffolds monorepo for zcli apps:new command

---

README.md

Updated installation prerequisites for Linux to include dependency on `libsecret` required by the `node-keytar` package.
Refer to [https://github.com/atom/node-keytar/tree/v7.5.0#on-linux](https://github.com/atom/node-keytar/tree/v7.5.0#on-linux) for further detail

docs: Updated installation prerequisites for Linux

---

scripts/release.sh

Remove auto doc gen for now given we have some custom docs which we don't want to be overriden.

Remove auto doc gen for now

---

package.json

There are occasional flakes in the functional tests (see eg here https://github.com/zendesk/zcli/runs/4425701072?check_suite_focus=true) basically caused by the fact that the default timeout of 2000ms is not enough.  We set the timeout to 5000ms in the standard unit tests, so let's use this option in our functional tests too.

Make sure that we use our mocha.opts in our functional tests too

---

packages/zcli-apps/src/lib/buildAppJSON.test.ts
packages/zcli-apps/src/lib/buildAppJSON.ts

@zendesk/vegemite 
`zcli apps:server` should handle a manifest wherein an installation location looks like this:
```
"location": {
"support": {
"ticket_sidebar": "assets/iframe.html"
}
},
```
and serve it locally if `?zcli_apps=true` is mounted to a test account.
Currently there is a javascript error presented with the current zcli tag, this is because for whatever reason this usecase was overlooked during development of zcli to date.
We should also continue to support manifest installation locations of the following form:
```
"location": {
"support": {
"ticket_sidebar": {
"autoHide": true,
"flexible": true,
"signed": true,
"url": "https://myapp.example.org/",
"size": {
"height": "220px"
}
}
}
},
```
Developer docs page: https://developer.zendesk.com/documentation/apps/app-developer-guide/ …

[VEG-1077] Handle case where installation location is a string and not an object

---

README.md

Adds a note to the README for Windows WSL users that are having issues running certain commands like `zcli login` and `zcli profiles` because WSL currently lack GUI support and ZCLI's credential manager depends on it.
Closes [#56](https://github.com/zendesk/zcli/issues/56)

docs: Add note to README on running ZCLI on WSL

---

package.json
yarn.lock

Adds the yarn-audit-fix package `[1]`, adds a command 'audit' to run it, and then runs 'yarn run audit'.
`[1]`: https://github.com/antongolub/yarn-audit-fix
```
>yarn audit
212 vulnerabilities found - Packages audited: 1510
Severity: 7 Low | 36 Moderate | 155 High | 14 Critical
```
```
>yarn audit
66 vulnerabilities found - Packages audited: 1557
Severity: 1 Low | 4 Moderate | 60 High | 1 Critical
```

Add yarn-audit-fix and then run it

---

README.md

It's currently hard to find and connect all the different parts of the Zendesk App Framework as it evolves...   conflicting scaffold repos exist (zendesk/app_scaffold and zendesk/app_scaffolds).
This should help people find the correct up-to-date scaffolds.

Add link to app scaffolds for ZAF

---

packages/zcli-core/src/lib/request.ts

I just used `zcli` for the first time and ran into the same problem as described in #11 . With the displayed error message it was not clear what I needed to do, because it is not obvious that `zcli` sends a request to the zendesk server. 
This PR adds the command one needs to run to the error message to make it more obvious what the user needs to do.
Side note: This `zcli login` step also doesn't seem to be documented in the [How-to Guide](https://developer.zendesk.com/documentation/apps/build-an-app/build-your-first-support-app/part-5-installing-the-app-in-zendesk-support/).

chore: improve error message when not logged in by telling user what to do

---

README.md
packages/zcli/README.md

Updates required node version to Node.js 14.17.3.
Updates Debian/Ubuntu `apt` command.
Updates the `zcli --version` command. `zcli -v` and `zcli version` are no longer supported.

docs: update required node version

---

scripts/release.sh

Make sure that we always publish to the main npmjs.com public registry.
Note, we use --@zendesk:registry=https://npmjs.com because configuration
in ~/.npmrc will override --registry=https://npmjs.com if set. [1]
[1]: https://stackoverflow.com/a/67691043

Always publish to npmjs.com main public registry

---

scripts/release.sh

Reverts zendesk/zcli#132
Lerna doesn't support the full medley on npm commands, so --@zendesk:registry=https://registry.npmjs.org or otherwise is nonsense to lerna.

Revert "Always publish to npmjs.com main public registry"

---

README.md
package.json
packages/zcli/package.json
scripts/link_dev.sh
yarn.lock

- fix: Pin TypeScript to <4.8 to avoid oclif/core error
- fix: Set up local ts-node stub for development
- fix: Tweak yarn link:bin for Cygwin
See [1]. oclif/core doesn't transpile using TypeScript 4.8 at the
moment.
[1] https://github.com/oclif/core/issues/482
To adopt TypeScript, we previously used ts-node [1] in [2] as our
shebang. However this required user to install ts-node as a sibling
global dependency and effectively stopped using transpiled JavaScript
files.
So in [3] we reverted back to node to fix the issue in distribution.
However locally when using `yarn/npm link`, it still links that very
same script to global binary directory. Since locally we don't keep the
JavaScript files (we only transpile them when packaging/publishing), it
rendered the `yarn link:bin` setup broken. …

Set up local ts-node stub for development

---

packages/zcli-apps/src/lib/buildAppJSON.test.ts
packages/zcli-apps/src/lib/buildAppJSON.ts

After running the command zcli apps:server, developers can use the [Send Notification to App API](https://developer.zendesk.com/api-reference/ticketing/apps/apps/#send-notification-to-app) to send messages to unpublished apps by setting the app_id parameter to 0 in the same way they can with Zendesk App Tools (ZAT)
JIRA: https://zendesk.atlassian.net/browse/VEG-1574
Here is a recording of **refreshing** the non published test app running on ZCLI  via the notify endpoint
https://share.getcloudapp.com/L1u6ojGk

[VEG-1574] Support sending notifications to unpublished apps in ZCLI

---

scripts/release.sh

Since we use yarn [1], it seems due to [2] it always respects our global
configuration and publishes @zendesk/ packages to our internal
repository despite having [3].
So let's do a check before publishing.
[1] https://github.com/zendesk/zcli/blob/011cbf414882bb8c15ba1a4913fe6cef1ebe29ed/lerna.json#L23
[2] https://github.com/yarnpkg/yarn/issues/5310
[3] https://github.com/zendesk/zcli/blob/011cbf414882bb8c15ba1a4913fe6cef1ebe29ed/lerna.json#L16-L18
Release tags should be on master branch only (although we are still on
beta). So ask user if they really want to publish if current branch is
not master.

Prevent publishing to internal repo or from non-`master` branches

---

scripts/release.sh

This is a tiny PR to check if the user is logged into NPM before running the release script. This is to prevent the possibility of publishing directly into artifactory in the event the user isn't logged into NPM
If we directly publish to artifactory it will mess up our mirrored setup and we have to ask packaging team to clean up.

[VEG-BAU]Check if logged to npm before publish

---

README.md
packages/zcli-core/package.json
packages/zcli/README.md
packages/zcli/package.json
yarn.lock

Recent @oclif plugin updates introduced @oclif/core v2 beta via a minor
version bump, e.g. [1].
Due to npm's dependency resolution algorithm, this consequently pulls in
@oclif/core v2 instead of v1, and it broke zcli.
So pinning these plugins' minor versions.
[1] https://github.com/oclif/plugin-plugins/blob/ee03e0f7ead2f1e6bf0ac03694314080367bbfd9/package.json#L9
Since we develop and test using lerna and yarn only (except for
publishing, which still involves npm under the hood sometimes), we
should recommend users to start with / migrate to yarn as well.
Closes #155
Closes #156

Pin @oclif plugins' minor versions down; doc updates to recommend yarn

---

.github/pull_request_template.md
.github/workflows/gh-ph.yml
.github/workflows/test.yml

[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Migrate Actions away from Node.js 12; set up `gh-ph`

---

package.json
packages/zcli-apps/package.json
packages/zcli-core/package.json
packages/zcli/package.json
yarn.lock

As much as we want to allow customers to get latest patches as soon as
possible, oclif on the other hand keeps breaking the Semantic Versioning
2.0.0 [1] contract, where breaking changes must lead to major version
bumps.
After fixing last breakage in [2][3] by pinning minor versions,
oclif/plugin-not-found also upgraded to oclif/core v2 [4] and this time
only patch version was bumped [5].
So being cautious this time and just pin all oclif dependencies to
exactly the same versions as those in the lock file.
[1] https://semver.org
[2] https://github.com/zendesk/zcli/pull/157
[3] https://github.com/zendesk/zcli/commit/3c73b5334e5604ba5c3ed40eb8eb76a758b3c0c3
[4] https://github.com/oclif/plugin-not-found/commit/b3176628b2dddd69c4419f8270fbb510231d3f8e
[5] …

fix: Pin all oclif dependencies to exact versions

---

packages/zcli-apps/src/commands/apps/create.ts
packages/zcli-apps/src/commands/apps/update.ts
packages/zcli-apps/src/lib/buildAppJSON.test.ts
packages/zcli-apps/src/lib/buildAppJSON.ts
packages/zcli-apps/src/types.ts
packages/zcli-apps/tests/functional/create.test.ts
packages/zcli-core/src/lib/request.ts

For requirements-only apps manifest.location isn’t required.
Example
```
{
"name": "Omniwear Instagram Channel",
"author": {
"name": "Omniwear",
"email": "support@omniwear.com",
"url": ""
},
"defaultLocale": "en",
"private": false,
"version": "1.0",
"singleInstall": true,
"requirementsOnly": true
}
```
If it's a requirements-only app we shouldn't check manifest.location in [update.ts](https://github.com/zendesk/zcli/blob/master/packages/zcli-apps/src/commands/apps/update.ts#L36) and [buildAppJSON.ts](https://github.com/zendesk/zcli/blob/master/packages/zcli-apps/src/lib/buildAppJSON.ts#L111)

fix: Fix apps:update and apps:server for requirements-only apps

---

.github/CODEOWNERS
packages/zcli-core/src/types.ts

This change aims at giving more freedom to the @zendesk/vikings team in case of `themes` related changes, and also remove the burden of review from the @zendesk/vegemite team for changes that do not impact `apps` packages.

CODEOWNERS update

---

packages/zcli-themes/src/lib/zass.test.ts
packages/zcli-themes/src/lib/zass.ts
packages/zcli-themes/tests/functional/preview.test.ts

This PR reimplements the zass formatter to be as close as a 1:1 match with the zass formatter in ZAT as possible.
*Context:*
We initially tried to simplify and have a fully `sass` based implementation of the zass formatter. However, that led to a few inconsistencies in the output, and it also led to a few problems with SASS [compilation errors](https://github.com/zendesk/zcli/issues/177#issuecomment-1574284189). 
ZAT basically just works based on find and replace so I ported that implementation over. It should also addressed the issue linked above.

Fix preview

---

docs/themes.md
packages/zcli-themes/package.json
packages/zcli-themes/src/commands/themes/import.ts
packages/zcli-themes/src/commands/themes/preview.ts
packages/zcli-themes/src/lib/createThemeImportJob.test.ts
packages/zcli-themes/src/lib/createThemeImportJob.ts
packages/zcli-themes/src/lib/createThemePackage.test.ts
packages/zcli-themes/src/lib/createThemePackage.ts
packages/zcli-themes/src/lib/getBrandId.test.ts
packages/zcli-themes/src/lib/getBrandId.ts
packages/zcli-themes/src/lib/pollJobStatus.test.ts
packages/zcli-themes/src/lib/pollJobStatus.ts
packages/zcli-themes/src/lib/preview.test.ts
packages/zcli-themes/src/lib/preview.ts
packages/zcli-themes/src/lib/uploadThemePackage.test.ts
packages/zcli-themes/src/lib/uploadThemePackage.ts
packages/zcli-themes/src/lib/validationErrorsToString.test.ts
packages/zcli-themes/src/lib/validationErrorsToString.ts
packages/zcli-themes/src/types.ts
packages/zcli-themes/tests/functional/import.test.ts
packages/zcli-themes/tests/functional/preview.test.ts
yarn.lock

This PR adds support for `zcli theme:import` and automates the steps necessary to import a theme into a target account/brand without having to leave the local development environment.

Support for zcli themes:import

---

docs/themes.md
packages/zcli-themes/src/commands/themes/update.ts
packages/zcli-themes/src/lib/createThemeUpdateJob.test.ts
packages/zcli-themes/src/lib/createThemeUpdateJob.ts
packages/zcli-themes/tests/functional/update.test.ts

Adding a new `zcli themes:update` command to update a previously imported theme.
Co-authored-by: André Alves <aalves@zendesk.com>
Co-authored-by: André Alves <aalves@zendesk.com>

Support for zcli themes:update

---

docs/themes.md
packages/zcli-themes/src/commands/themes/publish.ts
packages/zcli-themes/tests/functional/publish.test.ts

Adding a new `zcli themes:publish` command to set a theme as live.

Support for zcli themes:publish

---

.github/workflows/test.yml
README.md
packages/zcli/README.md

This PR:
- Updates docs to include themes;
- Updates CI to cache theme dependencies;

Add themes to docs + CI caching

---

packages/zcli-themes/src/lib/getBrandId.test.ts
packages/zcli-themes/src/lib/getBrandId.ts

The method used in the themes command for getting the brands was failing when the account has only one brand, since the API returns an integer and we were converting it to string only in the case of multiple brands available.

fix: fixed brand id getter when only one brand is present

---

docs/themes.md
packages/zcli-themes/src/commands/themes/delete.ts
packages/zcli-themes/src/commands/themes/import.ts
packages/zcli-themes/src/commands/themes/list.ts
packages/zcli-themes/src/commands/themes/publish.ts
packages/zcli-themes/src/commands/themes/update.ts
packages/zcli-themes/tests/functional/delete.test.ts
packages/zcli-themes/tests/functional/env.ts
packages/zcli-themes/tests/functional/import.test.ts
packages/zcli-themes/tests/functional/list.test.ts
packages/zcli-themes/tests/functional/publish.test.ts
packages/zcli-themes/tests/functional/update.test.ts

feat: support `themes:list` and `themes:delete` commands

---

packages/zcli-core/src/index.ts
packages/zcli/src/commands/login.ts
packages/zcli/src/commands/profiles/list.ts
packages/zcli/src/commands/profiles/use.ts

This PR fixes some imports introduced in #196, which were pointing to source files and weren't working on the built package.

fix: fixed imports for getAccount and getProfileAccount

---

docs/themes.md
packages/zcli-themes/src/commands/themes/preview.ts
packages/zcli-themes/src/lib/getAssets.ts
packages/zcli-themes/src/lib/getLocalServerBaseUrl.test.ts
packages/zcli-themes/src/lib/getLocalServerBaseUrl.ts
packages/zcli-themes/src/lib/getVariables.ts
packages/zcli-themes/src/lib/preview.test.ts
packages/zcli-themes/src/lib/preview.ts
packages/zcli-themes/src/types.ts

This PR adds the `--https-cert` and `--https-key` options for the `themes:preview` command, used for serving the theme assets from an HTTPS connection. This is needed for using the preview mode with Safari, which [doesn't allow mixed content for localhost](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#loading_locally_delivered_mixed-resources).

feat(themes): Added options for starting the preview mode in HTTPS

---

.github/workflows/test.yml
README.md
example/headless_ubuntu_zcli.Dockerfile

Update doc to explain how to use zcli in headless Linux: to use gonme-keyring, a keyring has to be created first before entries can be saved to it.
preview:

doc: update doc for running zcli in headless Linux

---

packages/zcli-themes/src/commands/themes/preview.ts
packages/zcli-themes/src/lib/preview.test.ts
packages/zcli-themes/src/lib/preview.ts
packages/zcli-themes/tests/functional/preview.test.ts

Up until now we were using the `env` variables to make the preview api request but we'd use the logged in profile to notify the user when the preview was ready. This resulted in a couple of bugs when:
- The logged in profile does not match the `env` variables
- The logged in profile is `undefined` and the task failed since we couldn't destruct the `subdomain` and `domain`
This PR makes sure we always use the `baseUrl` from `request.requestAPI` since that's where all the logic for [figuring out the proper auth configuration](https://github.com/zendesk/zcli/blob/master/packages/zcli-core/src/lib/request.ts#L12-L26) lives.

fix: `themes:preview` should respect the env variables

---

packages/zcli-apps/package.json
packages/zcli-core/package.json
packages/zcli-themes/package.json
yarn.lock

Reverts zendesk/zcli#234
Latest version of zcli has been causing a few issues with clients. We've gone through the commits and we are able to replicate the issue. It seems that `axios v1.7.2` is causing the api calls to fail with `Bad Request` error.
We are reverting this axios bump for now and bump it again later to a tested `latest` axios version.

[VEG-2375] - Revert bump axios to 1.7.2

---

packages/zcli-apps/tests/functional/new.test.ts
packages/zcli-core/src/lib/request.test.ts

Fix two unit test issues:
- [PR](https://github.com/zendesk/zcli/pull/238) dropping support for password based basic auth was merged but a test using axios@1.7.2 was not reverted. Test succeeded probably due to github action caching.
- For app scaffolding, webpack is dropped in favour of vite: https://github.com/zendesk/app_scaffolds/pull/16
Relevant discussion here: https://zendesk.slack.com/archives/CSQD7LRRT/p1722598486950829

[NO JIRA] fix: failing tests due to rebase and vite migration

---

packages/zcli-themes/src/lib/zass.test.ts
packages/zcli-themes/src/lib/zass.ts

I have just now noticed that we were only replacing the first instance of `lighten` or `darken` used in `style.css` when previewing themes 🤦🏼‍♂️.
I believe most developers are probably fully compiling their stylesheets with with SASS or something else and not relying on these functions at all and that's why we haven't had issue reports about it. However, this is a supported feature in Help Center so this PR fixes that bug.
I have also added some error handling for when `lighten` and `darken` are passed in undefined variables.
Co-authored-by: BrunoBFerreira <BrunoBFerreira@users.noreply.github.com>

fix(themes): replace all instances of `darken` and `lighten` in style.css

---

packages/zcli-apps/package.json
packages/zcli-apps/src/commands/apps/update.ts
yarn.lock

Fixes the following module resolution error:
```
./node_modules/.bin/zcli apps
(node:42933) [MODULE_NOT_FOUND] ModuleLoadError Plugin: @zendesk/zcli-apps: [MODULE_NOT_FOUND] require failed to load /Users/toanguyen/Code/zendesk/strategic-integrations-frontend/packages/deploy/node_modules/@zendesk/zcli-apps/dist/commands/apps/update.js: Cannot find module '@zendesk/zcli-core/src/lib/env'
```

fix: module resolution

---

packages/zcli-themes/package.json
yarn.lock

Due to not having the `sass` version fixed, the previous upgrade changed the version, which caused `sass` related tests to fail. To prevent this from happening again, this PR introduces a fix to pin the `sass` version for `zcli-themes`.

fix(tests): pin sass version for zcli themes

---

packages/zcli-themes/src/lib/pollJobStatus.ts

One of our customers is using ZCLI to automate their CI/CD and import themes. However, sometimes they are getting an error from the import command due to time out, but the theme is actually imported.
This happens because the `pollJobStatus` is using all the retries to fetch the job status but the job ends up finishing after all the checks are used. 
To prevent this from happening and in an attempt to make this command more stable, we are increasing the default value for retries, so that we continue polling for the status, giving more time for the job to update its status.

fix(themes): increase default retries in jobPollStatus

---

yarn.lock

Update `socks` to fix vulnerabilities.
Fix CVE-2024-29415
https://zendesk.atlassian.net/browse/APPS-7391

[APPS-7391] chore(deps): update `socks` to v2.8.4

---

.github/stale.yml

Adds a configuration for the zendesk stale GH app to automatically close out stale issues, PRs and branches.
See here for more details: https://github.com/zendesk/stale
The settings I've put are, if open for more than 90 days will be closed.
PRs and issues will receive a comment at that point and will be closed after 14 days if no activity has occurred.
I've also created a label `long-term` which can be applied to anything you wish to be saved.

Add stale config to automatically close stale PRs
