README.md
Update badge to point to NPM
Updates the NPM badge on README to point to NPM.
=> Docs: Update link on NPM badge

packages/zcli/package-lock.json, yarn.lock
At some stage during local dev, we mistakenly added package-lock.json to git repo. That was outdated and was being read by snyk for security scan. Most of those vulnerabilities are actually fixed. This PR just removes the outdated/unused package-lock file.
=> Remove unused pkg lock

.github/workflows/test.yml
We should make doubly sure that `zcli` can be run without errors in various environments.  Therefore, let's extend the github test action to facilitate this.
=> Add additional check to make sure that zcli can be built and run

.github/workflows/test.yml, package.json, packages/zcli-apps/package.json, packages/zcli-apps/src/commands/apps/new.ts, packages/zcli-core/package.json, packages/zcli/package.json
=> Fix types for new command

packages/zcli/package.json, packages/zcli/src/commands/login.ts, packages/zcli/src/commands/logout.ts, packages/zcli/src/commands/profiles/list.ts, packages/zcli/src/commands/profiles/remove.ts, packages/zcli/src/commands/profiles/use.ts
Update imports and add chalk in package.json. We missed out this one and it was being pulled from nested packages.
NOTE: ZCLI is broken for some users, this fixed the issue around login/logout and profiles.
=> Add chalk to package.json (for some reason we missed this out)

README.md
Let's see if we can squeeze this one in before 2022.
=> Update Copyright year

.github/CONTRIBUTING.md, README.md
Moved project details and developing workflow to CONTRIBUTING.md and updated guidance on README.md around contributing while ZCLI is in beta.
=> docs: updated README with contributing guidance

.github/workflows/test.yml, package.json, packages/zcli/package-lock.json, scripts/git_check.sh
There is an issue with the lock files for zcli, this may be causing issues for users.
`yarn install` in particular should not lead to a delta in these files.
```
>node -v
v14.17.3
```
Also adds a command to the test github action so as to fail the build if `git status` is non-empty after running `yarn install` earlier in the process.
Run `yarn install` in root and commit lock files.
=> Fix package-lock file and safeguard against future similar regressions

yarn.lock
Fixes an issue identified via SAST tool.
=> Run 'yarn run audit:fix'

package.json, packages/zcli-apps/src/commands/apps/new.ts, packages/zcli-apps/src/commands/apps/update.ts, packages/zcli-apps/src/lib/appPath.ts, packages/zcli-apps/src/lib/package.ts, packages/zcli-apps/src/utils/appConfig.ts, packages/zcli-apps/src/utils/fileUtils.ts, packages/zcli-apps/src/utils/manifest.ts, packages/zcli-core/src/lib/auth.ts, packages/zcli-core/src/lib/request.ts, packages/zcli/src/commands/profiles/remove.ts, yarn.lock
=> Remove @oclif/errors

package.json, packages/zcli-apps/package.json, packages/zcli/package.json
Add `zendesk` to package keywords.
=> Add zendesk to package.json keywords

package.json, packages/zcli-apps/package.json, packages/zcli-core/package.json, packages/zcli/package.json
=> Add command to package keyword

package.json, packages/zcli-apps/bin/run, packages/zcli-apps/package.json, packages/zcli-core/package.json, packages/zcli/bin/run, packages/zcli/package.json
- Replace ts-node shebang with node
- Add cli to package keywords (this commit is to ensure `lerna`
publishes all three packages)
=> Replace `ts-node` shebang with `node`

.github/workflows/test.yml
- e1495bcecea676fc04bdb96057fd09d548ea4a1f Use latest macOS in Actions to align with others
=> Use latest macOS in Actions to align with others

CHANGELOG.md, lerna.json, packages/zcli-apps/CHANGELOG.md, packages/zcli-apps/package.json, packages/zcli-core/CHANGELOG.md, packages/zcli-core/package.json, packages/zcli/CHANGELOG.md, packages/zcli/package.json
Release of the work done here https://github.com/zendesk/zcli/pull/146
=> [VEG-1574] send notifications to unpublished apps release

packages/zcli-apps/src/lib/buildAppJSON.test.ts
This code change is made simply to generate a diff between the last tag in order to create a new tag as the previous releases have not been released as intended.
Attempting to ship the work done in https://zendesk.atlassian.net/browse/VEG-742 & https://zendesk.atlassian.net/browse/VEG-1574
=> [VEG-bau] Make a change to enable a new release

packages/zcli-apps/package.json, packages/zcli-core/package.json, packages/zcli/package.json
This harmless code change is made to all three packages to simply to generate a diff with the last tag in order to create a new tag as the previous releases have not been released as intended.
Attempting to ship the work done in https://zendesk.atlassian.net/browse/VEG-742 & https://zendesk.atlassian.net/browse/VEG-1574
=> [VEG-bau] Enable release of latest ZCLI tag

packages/zcli-apps/package.json, packages/zcli-apps/src/commands/apps/new.ts, yarn.lock
This PR fixes the bug described in this [slack thread](https://zendesk.slack.com/archives/C1230V1CG/p1713196954122779).
=> [VEG-2314] Improve error handling and fix scaffolding bug

packages/zcli-apps/package.json, packages/zcli-core/package.json, packages/zcli-themes/package.json, yarn.lock
Let's bump to the latest axios, I believe that this is useful for a variety of reasons, such as 1) security, 2) supporting modern web apis
Let's bump to the latest axios, I believe that this is useful for a variety of
reasons, such as 1) security, 2) supporting modern web apis
=> [NO-JIRA] Bump axios to 1.7.2

packages/zcli-apps/src/utils/createApp.ts
Release `1.0.0-beta.v44` failed so we are adding a safe change so we could run another release.
=> [VEG-2375] - a token branch so that we can rerun a release

.mocharc.json
Currently our build are timing out: https://github.com/zendesk/zcli/actions/runs/10675846225/job/29647437934
In this PR we bump the test timeout.
=> fix: bump timeout for tests

docs/login.md
=> Trigger NPM release

packages/zcli-apps/package.json, yarn.lock
=> Remove zcli-core as dependecy for apps

README.md
=> docs: update node.js version in readme file

package.json, packages/zcli/package.json
=> [VEG-2450] specify engine within the zcli package

docs/themes.md
Docs were copied from themes:import, tested syntax and updated .md file to match functioning code.
=> docs: updated example in themes:list

package.json, yarn.lock
=> chore: fix `yarn:check` issues

packages/zcli-apps/src/utils/uploadApp.ts
=> fix: fix `uploadApp.js` when there is no installed apps

.github/CODEOWNERS, .github/CODE_OF_CONDUCT.md, package.json, packages/zcli-apps/package.json, packages/zcli-core/package.json, packages/zcli/package.json
Ownership of this project has been transferred to the @zendesk/wattle team.
Updating references accordingly.
=> Update author references to wattle

.github/workflows/stale.yml
=> Fix Stale GH action
